/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 /home/obx/Documents/Work/Graphics/asus_rog_strix_scar_17_2023_g733_gaming_laptop.glb -o /home/obx/Documents/Work/Graphics/asus_rog_strix_scar_17_2023_g733_gaming_laptop.tsx --types 
Author: RaflyNaHa (https://sketchfab.com/RaflyNaHa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/asus-rog-strix-scar-17-2023-g733-gaming-laptop-51eca7b2e5884c4087f3499e523d5184
Title: Asus ROG Strix Scar 17 (2023) G733 Gaming Laptop
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_83: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_89: THREE.Mesh
    Object_91: THREE.Mesh
    Object_93: THREE.Mesh
    Object_95: THREE.Mesh
    Object_97: THREE.Mesh
    Object_99: THREE.Mesh
    Object_101: THREE.Mesh
    Object_102: THREE.Mesh
    Object_103: THREE.Mesh
    Object_105: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_109: THREE.Mesh
    Object_111: THREE.Mesh
    Object_113: THREE.Mesh
    Object_115: THREE.Mesh
    Object_117: THREE.Mesh
    Object_119: THREE.Mesh
  }
  materials: {
    Logo_AMD: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    Merah: THREE.MeshStandardMaterial
    Lightbar: THREE.MeshStandardMaterial
    Teks_Bawah: THREE.MeshStandardMaterial
    Metal_1: THREE.MeshStandardMaterial
    Layar: THREE.MeshStandardMaterial
    Touchpad: THREE.MeshStandardMaterial
    Logo: THREE.MeshStandardMaterial
    Web_Cam: THREE.MeshStandardMaterial
    Logo_Text: THREE.MeshStandardMaterial
    Metal_2: THREE.MeshStandardMaterial
    Keyboard: THREE.MeshStandardMaterial
    Bawah: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    Hole: THREE.MeshStandardMaterial
    material_0: THREE.MeshStandardMaterial
    Logo_RTX: THREE.MeshStandardMaterial
    Logo_ROG: THREE.MeshStandardMaterial
    Indikator: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/asus_rog_strix_scar_17_2023_g733_gaming_laptop.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 3.395, -0.325]} scale={2.299}>
        <group position={[0.368, -0.441, -0.295]} rotation={[0, -0.747, 0]} scale={0.06}>
          <mesh geometry={nodes.Object_9.geometry} material={materials.Merah} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Lightbar} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Lightbar} />
        </group>
        <group position={[0.765, -0.447, -0.486]} rotation={[-0.175, 0, 0]} scale={[0.435, 0.668, 0.435]}>
          <group position={[-1.76, 0.892, -0.001]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.651]}>
            <mesh geometry={nodes.Object_19.geometry} material={materials.Layar} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.Touchpad} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.Metal_1} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.Logo} />
            <mesh geometry={nodes.Object_23.geometry} material={materials.Web_Cam} />
          </group>
          <mesh geometry={nodes.Object_17.geometry} material={materials.Metal_1} position={[-3.381, 0.111, 0.016]} scale={[1.035, 0.68, 1]} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.Logo_Text} position={[-3.042, 0.158, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[0.057, 0.057, 0.037]} />
        </group>
        <group position={[0, -0.446, -0.009]} scale={0.435}>
          <mesh geometry={nodes.Object_27.geometry} material={materials.Metal_1} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.Touchpad} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.Metal_2} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.Lightbar} />
        </group>
        <group position={[0.6, -0.441, -0.091]} scale={0.032}>
          <mesh geometry={nodes.Object_82.geometry} material={materials.Keyboard} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.Bawah} />
        </group>
        <group position={[0, -0.517, -0.003]} rotation={[-Math.PI, 0, 0]} scale={0.435}>
          <mesh geometry={nodes.Object_101.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_102.geometry} material={materials.Metal_1} />
          <mesh geometry={nodes.Object_103.geometry} material={materials.Hole} />
        </group>
        <group position={[-0.62, -0.499, 0.44]} scale={0.435}>
          <mesh geometry={nodes.Object_105.geometry} material={materials.Metal_1} />
          <mesh geometry={nodes.Object_106.geometry} material={materials.Bawah} />
        </group>
        <group position={[0.872, -0.443, 0.49]} rotation={[-Math.PI, 0.684, 0]} scale={[0.765, 0.435, 0.001]}>
          <mesh geometry={nodes.Object_108.geometry} material={materials.Logo} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.material_0} />
        </group>
        <mesh geometry={nodes.Object_5.geometry} material={materials.Logo_AMD} position={[-0.636, -0.445, 0.153]} scale={0.045} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material} position={[0.612, -0.441, -0.357]} scale={0.008} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Teks_Bawah} position={[-0.653, -0.524, -0.441]} rotation={[0, 0, Math.PI]} scale={0.105} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Keyboard} position={[-0.476, -0.441, -0.019]} scale={0.032} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Keyboard} position={[-0.512, -0.441, -0.092]} scale={0.032} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Keyboard} position={[-0.531, -0.441, -0.164]} scale={0.032} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Keyboard} position={[-0.642, -0.441, -0.237]} scale={0.032} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Keyboard} position={[-0.642, -0.441, -0.164]} scale={0.032} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Keyboard} position={[-0.642, -0.441, -0.091]} scale={0.032} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Keyboard} position={[-0.596, -0.441, -0.019]} scale={0.032} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Keyboard} position={[-0.642, -0.441, 0.055]} scale={0.032} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Keyboard} position={[-0.549, -0.441, 0.055]} scale={0.032} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Keyboard} position={[-0.328, -0.441, 0.055]} scale={0.032} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.Keyboard} position={[0.044, -0.441, 0.055]} scale={0.032} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.Keyboard} position={[0.119, -0.441, 0.055]} scale={0.032} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.Keyboard} position={[0.343, -0.441, -0.091]} scale={0.032} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.Keyboard} position={[0.288, -0.441, -0.019]} scale={0.032} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.Keyboard} position={[0.305, -0.441, -0.164]} scale={0.032} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Keyboard} position={[0.352, -0.441, -0.237]} scale={0.032} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.Keyboard} position={[-0.642, -0.441, -0.31]} scale={0.032} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.Keyboard} position={[-0.494, -0.441, -0.31]} scale={0.032} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Keyboard} position={[-0.174, -0.441, -0.31]} scale={0.032} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.Keyboard} position={[0.146, -0.441, -0.31]} scale={0.032} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.Keyboard} position={[0.381, -0.441, 0.093]} scale={0.032} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.Keyboard} position={[0.303, -0.441, 0.044]} scale={0.032} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.Keyboard} position={[0.478, -0.441, 0.055]} scale={0.032} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.Keyboard} position={[0.6, -0.441, 0.055]} scale={0.032} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.Keyboard} position={[0.6, -0.441, -0.019]} scale={0.032} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.Keyboard} position={[0.6, -0.441, -0.164]} scale={0.032} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.Keyboard} position={[0.6, -0.441, -0.237]} scale={0.032} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.Keyboard} position={[0.442, -0.441, -0.31]} scale={0.032} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.Keyboard} position={[0.661, -0.441, -0.237]} scale={0.032} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.Keyboard} position={[0.661, -0.441, -0.164]} scale={0.032} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.Keyboard} position={[0.661, -0.441, -0.019]} scale={0.032} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.Keyboard} position={[-0.494, -0.441, -0.372]} scale={0.032} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.Keyboard} position={[0.612, -0.441, -0.357]} scale={0.034} />
        <mesh geometry={nodes.Object_111.geometry} material={materials.Logo_RTX} position={[-0.51, -0.445, 0.153]} scale={0.045} />
        <mesh geometry={nodes.Object_113.geometry} material={materials.Logo_ROG} position={[-0.423, -0.43, -0.538]} rotation={[2.918, 0, Math.PI]} scale={0.435} />
        <mesh geometry={nodes.Object_115.geometry} material={materials.Merah} position={[0.621, -0.441, -0.387]} scale={0.025} />
        <mesh geometry={nodes.Object_117.geometry} material={materials.Indikator} position={[0.148, -0.441, -0.412]} scale={0.025} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.Teks_Bawah} position={[0.686, -0.524, -0.468]} scale={[-0.021, 0.021, 0.021]} />
      </group>
    </group>
  )
}

useGLTF.preload('/asus_rog_strix_scar_17_2023_g733_gaming_laptop.glb')
